# Generated by Django 5.2.5 on 2025-09-15 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
