# Generated by Django 5.2.5 on 2025-10-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_comuna_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='digito_verificador',
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
