# Generated by Django 5.2.5 on 2025-10-20 22:35

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_remove_lector_digito_verificador_alter_lector_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='correo_lector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[biblioteca.models.validar_rut]),
        ),
    ]
