# Generated by Django 5.2.5 on 2025-11-03 19:49

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_lector_correo_lector_lector_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None, validators=[biblioteca.models.validar_mayor_edad]),
        ),
    ]
